name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main

env:
  # Registry/Repository As Required
  DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
  DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      # Initial Code Checkout
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog OSS 
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true 
        with: 
          path: ./ 
          extra_args: --debug,--results=verified,unknown
      - name: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
