FROM node:22-alpine@sha256:0a7108bf6c7bf5de370ffb1a3ed6be93d405b43ff159f681a8d18c0e2bc2e402
WORKDIR /app
COPY ./site /app/
* RUN rm -rf /app/node_modules
RUN npm install ejs && npm install
CMD ["npm","start"]
